### ISSUE TITLE
Issues while installing in OCaml 4.07 

### ISSUE THREAD

**Issue by abhi18av** [nv-vn/TelegraML#17]
Hi @nv-vn 

I love this package! I was really looking forward to some well written API client in `OCaml` and that's how I found this - thanks a lot man :)

However, I'd really like to use this with the latest `OCaml - 4.07` and so far when I try to install this in my system it throws the following error 

```
root@tuffy:~/workspace# opam install telegram
The following dependencies couldn't be met:  - telegraml → batteries >= 2.4.0 → ocaml < 4.07.0
      base of this switch (use `--unlock-base' to force)

```

Then I saw the codebase and I think the minor use of `batteries.string` module could easily be replaced by the standard module itself, if I'm not wrong. 

Could you please guide me here a little bit, I'm quite new to `OCaml`

**Comment by OhadRau** [comment]
Hi, thanks for bringing this up. Right now, I'm the primary maintainer of this repository (though I'm by no means active). I can try to look at this in the next hour or so when I get a chance. This should definitely be an easy fix and I'll try to get it out ASAP

**Comment by OhadRau** [comment]
An easy fix should hopefully be through [batteries.2.9.0 which was just released the other day](https://github.com/ocaml/opam-repository/tree/master/packages/batteries/batteries.2.9.0), but for some reason I can't get OPAM to recognize this package even after updating this repository. I'm guessing you're currently having the same problem so I'm looking into this right now.

**Comment by OhadRau** [comment]
Ok, quick update, so the reason that package isn't detected is because it requires OPAM 2.0+. Since you're most likely also running OPAM 2.0, I'm gonna assume you're probably on debian or another debian derivative like Ubuntu.

The easiest fix (if you want to get started ASAP) is to uninstall OPAM thru apt and install it manually. However that's a really annoying so I'm currently updating the lib to remove the dependency on Batteries. I suspect that in the near future this will break again because of other packages updating to OPAM 2.0, but I want to rewrite this library in the near future anyways.

I think I'm pretty much done with the updates but I'm currently testing to make sure everything works as intended. Hopefully I'll have the new package merged into OPAM in the next ~24 hours

**Comment by OhadRau** [comment]
https://github.com/ocaml/opam-repository/pull/12765

**Comment by abhi18av** [comment]
@OhadRau , thanks a lot for the quick response :)

**Comment by OhadRau** [comment]
Forgot to post this update here, but I basically need to upgrade to OPAM 2.0 to push to the opam repo. Easiest method to install would probably be cloning this repo and pinning the package in OPAM (opam pin add command) since getting it updated in the repo won't help on 1.2. Let me know if that doesn't work for you

**Comment by abhi18av** [comment]
It does work fine for me now :)
